### ISSUE TITLE
Explans differences between different tool chains

### ISSUE THREAD

**Issue by sschuberth** [raspberrypi/tools#30] opened 2015-02-09 09:51 UTC
Please add a root-level REAME.md file that explains the differences between the four different toolchains contained in the `arm-bcm2708` directory. (If I knew the difference, I would have happily filed a PR.)

**Comment by drewreece** [comment] 2015-04-01 17:56
Seems like a possible duplicate of https://github.com/raspberrypi/tools/issues/10

**Comment by popcornmix** [comment] 2015-04-01 18:07
Yes duplicate of #10

**Closed by popcornmix** 2015-04-01 18:07 UTC
