### ISSUE TITLE
Toolchain is not updated.

### ISSUE THREAD

**Issue by xieyubo** [raspberrypi/tools#83] opened 2017-09-11 17:38 UTC
Just notice, raspberry has released a new version raspbian (based on Debian Stretch) on Sep 7th, 2017). The default gcc version on this release is 6.3.0. But seems we haven't updated the cross compile tool chain.

**Comment by popcornmix** [comment] 2017-09-12 14:10
Duplicate of https://github.com/raspberrypi/tools/issues/81

**Closed by popcornmix** 2017-09-12 14:10 UTC
